name: anyup

channels:
  - conda-forge

dependencies:
  - python =3.12
  - einops
  - matplotlib
  - numpy
  - timm
  - plotly
  - tensorboard
  - hydra-core
  - ipykernel
  - rich
  - scikit-learn
  - torchmetrics
  - transformers
  # NOTE: Installing the pytorch package from conda-forge will generally
  # give you the most optimized version for your system, if you have a
  # modern enough OS and CUDA version (CUDA >= 12). For older versions,
  # you can specify the CUDA version by pinning libtorch.
  # For example, add this line for CUDA 11 version:
  # - libtorch=*=cuda11*
  # or, to enforce a CPU installation, change the package below to
  # - pytorch=*=cpu*
  - pytorch
  - torchvision
  - pip:
      - natten
